version: "3.8"

services:
  mysqldb:
    container_name : mysql
    image: mysql:8.2.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}      
      - MYSQL_ROOT_HOST=%
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - dbpetstore:/var/lib/mysql
    networks:
      - nwpetstore
  app:
    container_name : java
    depends_on:
      - mysqldb
    build: ./petstore
    restart: on-failure
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{ 
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}", 
        "spring.datasource.username" : "${MYSQLDB_USER}", 
        "spring.datasource.password" : "${MYSQLDB_ROOT_PASSWORD}",
        "spring.jpa.hibernate.ddl-auto" : "update", 
        "spring.jpa.defer-datasource-initialization" : "true",
        "spring.sql.init.mode" : "always",
        "spring.security.oauth2.client.registration.google.client-id" : "${GOOGLE_OAUTH2_ID}", 
        "spring.security.oauth2.client.registration.google.client-secret" : "${GOOGLE_OAUTH2_SECRET}",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect" }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - nwpetstore
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysqldb
    ports:
      - ${PHPMYADMIN_LOCAL_PORT}:${PHPMYADMIN_DOCKER_PORT}
    environment:
      - PMA_HOST=mysqldb
    networks:
      - nwpetstore

volumes:
  dbpetstore:

networks:
  nwpetstore: